"use strict";
var isOne = false;
console.log(isOne);
var decimal = 10;
var hex = 100;
var binary = 200;
var octal = 300;
console.log(decimal);
console.log(hex);
console.log(binary);
console.log(octal);
var color = "blue";
color = "red";
console.log(color);
var fullName = "Blackcend";
var age = 30;
var sentence = "\n    Hello, my name is " + fullName + ". My age is " + (age + 1) + ".\n";
console.log(sentence);
var list = [1, 2, 3];
var list1 = [1, 2, 3];
console.log(list1);
var x;
x = ["hello", 10];
console.log(x[0].substring(1));
x[3] = "World";
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Yellow"] = 1] = "Yellow";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Blue;
console.log(c);
var someValue = "this is a string";
var strLength = someValue.length;
var strLength1 = someValue.length;
console.log(strLength);
//# sourceMappingURL=basic-type.js.map